create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.users (
  id uuid primary key default gen_random_uuid(),
  username text,
  full_name text,
  email text unique,
  phone text,
  role text not null default 'customer',
  active boolean not null default true,
  password_hash text,
  cart jsonb not null default '[]'::jsonb,
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  name text,
  email text unique,
  phone text,
  address text,
  city text,
  region text,
  customer_type text not null default 'retail',
  credit_limit numeric(12,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  company text,
  contact_person text,
  email text,
  phone text,
  address text,
  payment_terms text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  category text,
  description text,
  price numeric(12,2) not null default 0,
  cost_price numeric(12,2) not null default 0,
  stock integer not null default 0,
  reorder_level integer not null default 10,
  sku text,
  barcode text,
  color text,
  image text,
  image1 text,
  image2 text,
  image3 text,
  image4 text,
  image5 text,
  spec_display text,
  spec_processor text,
  spec_ram text,
  spec_storage text,
  spec_battery text,
  spec_back_camera text,
  spec_front_camera text,
  spec_os text,
  spec_weight text,
  spec_extras text,
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  customer_name text,
  customer_email text,
  customer_phone text,
  customer_city text,
  customer_region text,
  delivery_address text,
  delivery_method text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2),
  subtotal_amount numeric(12,2),
  vat_amount numeric(12,2),
  total_amount numeric(12,2) not null default 0,
  payment_method text,
  payment_reference text,
  dpo_trans_ref text,
  status text not null default 'Pending',
  loyalty_discount numeric(12,2) not null default 0,
  coupon_code text,
  coupon_discount numeric(12,2),
  notes text,
  stock_reserved boolean not null default false,
  reservation_expires_at timestamptz,
  stock_returned boolean not null default false,
  courier_company text,
  waybill_number text,
  date_dispatched timestamptz,
  picked_up_at timestamptz,
  paid_at timestamptz,
  delivery_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_imeis (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  sku text,
  color text,
  imei text,
  serial_number text,
  image_url text,
  status text not null default 'available',
  sold_at timestamptz,
  order_id uuid references public.orders(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  movement_type text not null,
  quantity integer not null default 0,
  reference_type text,
  reference_id text,
  notes text,
  user_name text,
  created_at timestamptz not null default now()
);

create table public.till_shifts (
  id bigint generated by default as identity primary key,
  till_id integer not null default 1,
  cashier_name text,
  opening_float numeric(12,2) not null default 0,
  opening_time timestamptz not null default now(),
  closing_time timestamptz,
  expected_cash numeric(12,2),
  actual_cash numeric(12,2),
  cash_variance numeric(12,2),
  total_sales numeric(12,2),
  cash_sales numeric(12,2),
  card_sales numeric(12,2),
  transaction_count integer not null default 0,
  status text not null default 'Open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.expenses (
  id bigint generated by default as identity primary key,
  category text,
  description text not null,
  amount numeric(12,2) not null default 0,
  supplier_vendor text,
  receipt_number text,
  payment_method text,
  tax_deductible boolean not null default false,
  notes text,
  expense_date date not null default current_date,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.hero_images (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  link_url text,
  order_index integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.service_charges (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  description text,
  category text not null default 'general',
  price numeric(12,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.invoices (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text,
  customer_email text,
  items jsonb not null default '[]'::jsonb,
  subtotal_amount numeric(12,2) not null default 0,
  vat_amount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  due_date date,
  status text not null default 'draft',
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.purchase_orders (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier_name text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12,2) not null default 0,
  notes text,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.grvs (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier_name text,
  supplier_invoice_no text,
  invoice_date date,
  po_number text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12,2) not null default 0,
  notes text,
  status text not null default 'received',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null default 'percentage',
  discount_value numeric(12,2) not null default 0,
  discount_percent numeric(12,2),
  min_purchase numeric(12,2) not null default 0,
  max_uses integer,
  times_used integer not null default 0,
  valid_from timestamptz,
  valid_until timestamptz,
  notes text,
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coupon_usage (
  id bigint generated by default as identity primary key,
  coupon_id bigint references public.coupons(id) on delete set null,
  coupon_code text,
  order_id uuid references public.orders(id) on delete set null,
  customer_name text,
  customer_email text,
  discount_amount numeric(12,2),
  order_total numeric(12,2),
  used_at timestamptz not null default now()
);

create table public.blocked_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  reason text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  message text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.customers (id, name, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', new.email),
    new.email,
    new.raw_user_meta_data->>'phone'
  )
  on conflict (id) do nothing;

  insert into public.users (id, username, full_name, email, phone, role, active, password_hash)
  values (
    new.id,
    split_part(new.email, '@', 1),
    coalesce(new.raw_user_meta_data->>'name', new.email),
    new.email,
    new.raw_user_meta_data->>'phone',
    'customer',
    true,
    'supabase-auth-managed'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users u
    where u.active = true
      and (
        u.id = auth.uid()
        or lower(u.email) = lower(coalesce(auth.jwt()->>'email', ''))
      )
      and lower(u.role) in ('admin', 'owner', 'manager')
  );
$$;

create or replace function public.protect_user_admin_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  new.role := old.role;
  new.active := old.active;
  new.password_hash := old.password_hash;
  return new;
end;
$$;

create or replace function public.limit_customer_product_updates()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  new.name := old.name;
  new.brand := old.brand;
  new.category := old.category;
  new.description := old.description;
  new.price := old.price;
  new.cost_price := old.cost_price;
  new.reorder_level := old.reorder_level;
  new.sku := old.sku;
  new.barcode := old.barcode;
  new.color := old.color;
  new.image := old.image;
  new.image1 := old.image1;
  new.image2 := old.image2;
  new.image3 := old.image3;
  new.image4 := old.image4;
  new.image5 := old.image5;
  new.spec_display := old.spec_display;
  new.spec_processor := old.spec_processor;
  new.spec_ram := old.spec_ram;
  new.spec_storage := old.spec_storage;
  new.spec_battery := old.spec_battery;
  new.spec_back_camera := old.spec_back_camera;
  new.spec_front_camera := old.spec_front_camera;
  new.spec_os := old.spec_os;
  new.spec_weight := old.spec_weight;
  new.spec_extras := old.spec_extras;
  new.active := old.active;
  new.featured := old.featured;
  return new;
end;
$$;

create or replace function public.validate_coupon(p_code text, p_cart_total numeric)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.coupons%rowtype;
  discount_amount numeric(12,2);
begin
  select * into c
  from public.coupons
  where upper(code) = upper(trim(p_code))
    and active = true
    and (valid_from is null or valid_from <= now())
    and (valid_until is null or valid_until >= now())
    and (max_uses is null or times_used < max_uses)
  limit 1;

  if not found then
    return jsonb_build_object('valid', false, 'message', 'Coupon is invalid or expired');
  end if;

  if p_cart_total < c.min_purchase then
    return jsonb_build_object('valid', false, 'message', 'Minimum purchase not met');
  end if;

  if c.discount_type = 'fixed' then
    discount_amount := least(c.discount_value, p_cart_total);
  else
    discount_amount := round(p_cart_total * (c.discount_value / 100), 2);
  end if;

  return jsonb_build_object(
    'valid', true,
    'coupon_id', c.id,
    'code', c.code,
    'discount_type', c.discount_type,
    'discount_value', c.discount_value,
    'discount_amount', discount_amount
  );
end;
$$;

create or replace function public.validate_voucher(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.coupons%rowtype;
begin
  select * into c
  from public.coupons
  where upper(code) = upper(trim(p_code))
    and active = true
    and discount_type = 'percentage'
    and (valid_from is null or valid_from <= now())
    and (valid_until is null or valid_until >= now())
    and (max_uses is null or times_used < max_uses)
  limit 1;

  if not found then
    return jsonb_build_object('valid', false, 'message', 'Voucher is invalid or expired');
  end if;

  return jsonb_build_object(
    'valid', true,
    'code', c.code,
    'discount_percent', coalesce(c.discount_percent, c.discount_value)
  );
end;
$$;

do $$
declare
  t text;
begin
  foreach t in array array[
    'users', 'customers', 'suppliers', 'products', 'orders', 'product_imeis',
    'stock_movements', 'till_shifts', 'expenses', 'settings', 'hero_images',
    'service_charges', 'invoices', 'purchase_orders', 'grvs', 'coupons',
    'coupon_usage', 'blocked_users', 'messages'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end;
$$;

create policy "public reads active products" on public.products
for select using (active = true or public.is_admin());
create policy "admins manage products" on public.products
for all using (public.is_admin()) with check (public.is_admin());
create policy "authenticated adjusts product stock" on public.products
for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create policy "public reads active hero images" on public.hero_images
for select using (active = true or public.is_admin());
create policy "admins manage hero images" on public.hero_images
for all using (public.is_admin()) with check (public.is_admin());

create policy "public reads active service charges" on public.service_charges
for select using (active = true or public.is_admin());
create policy "admins manage service charges" on public.service_charges
for all using (public.is_admin()) with check (public.is_admin());

create policy "authenticated reads own orders" on public.orders
for select using (public.is_admin() or user_id = auth.uid() or lower(customer_email) = lower(coalesce(auth.jwt()->>'email', '')));
create policy "authenticated creates own orders" on public.orders
for insert with check (auth.role() = 'authenticated' and (user_id = auth.uid() or user_id is null));
create policy "authenticated updates own orders" on public.orders
for update using (public.is_admin() or user_id = auth.uid() or lower(customer_email) = lower(coalesce(auth.jwt()->>'email', '')))
with check (public.is_admin() or user_id = auth.uid() or lower(customer_email) = lower(coalesce(auth.jwt()->>'email', '')));
create policy "authenticated deletes own pending orders" on public.orders
for delete using (public.is_admin() or (user_id = auth.uid() and status = 'Pending'));

create policy "authenticated reads available imeis" on public.product_imeis
for select using (public.is_admin() or status = 'available');
create policy "authenticated updates imeis" on public.product_imeis
for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "admins manage imeis" on public.product_imeis
for all using (public.is_admin()) with check (public.is_admin());

create policy "authenticated reads own customer" on public.customers
for select using (public.is_admin() or id = auth.uid() or lower(email) = lower(coalesce(auth.jwt()->>'email', '')));
create policy "authenticated updates own customer" on public.customers
for update using (public.is_admin() or id = auth.uid()) with check (public.is_admin() or id = auth.uid());
create policy "admins manage customers" on public.customers
for all using (public.is_admin()) with check (public.is_admin());

create policy "authenticated reads own user row" on public.users
for select using (public.is_admin() or id = auth.uid());
create policy "authenticated updates own user row" on public.users
for update using (public.is_admin() or id = auth.uid()) with check (public.is_admin() or id = auth.uid());
create policy "admins manage user rows" on public.users
for all using (public.is_admin()) with check (public.is_admin());

create policy "authenticated reads coupons" on public.coupons
for select using (active = true or public.is_admin());
create policy "admins manage coupons" on public.coupons
for all using (public.is_admin()) with check (public.is_admin());
create policy "authenticated logs coupon usage" on public.coupon_usage
for insert with check (auth.role() = 'authenticated');
create policy "admins read coupon usage" on public.coupon_usage
for select using (public.is_admin());

create policy "authenticated checks blocked users" on public.blocked_users
for select using (auth.role() = 'authenticated' or public.is_admin());
create policy "admins manage blocked users" on public.blocked_users
for all using (public.is_admin()) with check (public.is_admin());

create policy "anyone creates messages" on public.messages
for insert with check (true);
create policy "admins read messages" on public.messages
for select using (public.is_admin());

do $$
declare
  t text;
begin
  foreach t in array array[
    'suppliers', 'stock_movements', 'till_shifts', 'expenses', 'settings',
    'invoices', 'purchase_orders', 'grvs'
  ]
  loop
    execute format('create policy "admins manage %I" on public.%I for all using (public.is_admin()) with check (public.is_admin())', t, t);
  end loop;
end;
$$;

create index products_active_created_idx on public.products (active, created_at desc);
create index products_name_idx on public.products (name);
create index orders_customer_email_idx on public.orders (lower(customer_email));
create index orders_created_at_idx on public.orders (created_at desc);
create index product_imeis_product_status_idx on public.product_imeis (product_id, status);
create index coupons_code_idx on public.coupons (upper(code));

do $$
declare
  t text;
begin
  foreach t in array array[
    'users', 'customers', 'suppliers', 'products', 'orders', 'product_imeis',
    'till_shifts', 'expenses', 'settings', 'hero_images', 'service_charges',
    'invoices', 'purchase_orders', 'grvs', 'coupons'
  ]
  loop
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t);
  end loop;
end;
$$;

create trigger protect_user_admin_fields
before update on public.users
for each row execute function public.protect_user_admin_fields();

create trigger limit_customer_product_updates
before update on public.products
for each row execute function public.limit_customer_product_updates();

grant usage on schema public to anon, authenticated;
grant select on public.products, public.hero_images, public.service_charges, public.coupons to anon, authenticated;
grant insert on public.messages to anon, authenticated;
grant all on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.validate_coupon(text, numeric) to anon, authenticated;
grant execute on function public.validate_voucher(text) to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('Images', 'Images', true)
on conflict (id) do update set public = excluded.public;

create policy "public reads Images bucket" on storage.objects
for select using (bucket_id = 'Images');

create policy "admins manage Images bucket" on storage.objects
for all using (bucket_id = 'Images' and public.is_admin())
with check (bucket_id = 'Images' and public.is_admin());
