create table if not exists public.special_order_requests (
  id bigint generated by default as identity primary key,
  customer_name text,
  customer_email text,
  customer_phone text,
  requested_product text not null,
  preferred_color_storage text,
  target_budget numeric(12,2),
  city text,
  needed_by date,
  notes text,
  status text not null default 'New request',
  quoted_price numeric(12,2),
  deposit_amount numeric(12,2),
  supplier_reference text,
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_alert_requests (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  preferred_color text,
  customer_name text,
  customer_email text,
  customer_phone text,
  channel text not null default 'WhatsApp',
  status text not null default 'Waiting',
  notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists special_order_requests_status_idx on public.special_order_requests (status, created_at desc);
create index if not exists stock_alert_requests_product_status_idx on public.stock_alert_requests (product_id, status, created_at desc);

alter table public.special_order_requests enable row level security;
alter table public.stock_alert_requests enable row level security;

drop policy if exists "anyone creates special orders" on public.special_order_requests;
create policy "anyone creates special orders" on public.special_order_requests
for insert with check (true);

drop policy if exists "admins manage special orders" on public.special_order_requests;
create policy "admins manage special orders" on public.special_order_requests
for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "anyone creates stock alerts" on public.stock_alert_requests;
create policy "anyone creates stock alerts" on public.stock_alert_requests
for insert with check (true);

drop policy if exists "admins manage stock alerts" on public.stock_alert_requests;
create policy "admins manage stock alerts" on public.stock_alert_requests
for all using (public.is_admin()) with check (public.is_admin());

grant insert on public.special_order_requests to anon, authenticated;
grant insert on public.stock_alert_requests to anon, authenticated;
grant select, update, delete on public.special_order_requests to authenticated;
grant select, update, delete on public.stock_alert_requests to authenticated;
grant usage, select on sequence public.special_order_requests_id_seq to anon, authenticated;
grant usage, select on sequence public.stock_alert_requests_id_seq to anon, authenticated;
