-- IQ-Retail-style modules: Quotes, Layby, Debtor/Creditor ledger, Stock Takes.
-- All admin-managed (gated by public.is_admin()); authenticated role granted.

-- ---------------------------------------------------------------------------
-- Quotes (sales quotations)
-- ---------------------------------------------------------------------------
create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  quote_number text,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text,
  customer_email text,
  customer_phone text,
  items jsonb not null default '[]'::jsonb,
  subtotal_amount numeric(12,2) not null default 0,
  vat_amount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  status text not null default 'draft',        -- draft | sent | accepted | declined | expired | converted
  valid_until date,
  notes text,
  converted_order_id uuid references public.orders(id) on delete set null,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Laybys (instalment lay-bye sales)
-- ---------------------------------------------------------------------------
create table if not exists public.laybys (
  id bigint generated by default as identity primary key,
  layby_number text,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text,
  customer_phone text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12,2) not null default 0,
  deposit_amount numeric(12,2) not null default 0,
  paid_amount numeric(12,2) not null default 0,
  balance_amount numeric(12,2) not null default 0,
  payments jsonb not null default '[]'::jsonb,  -- [{amount, method, date, by}]
  status text not null default 'active',        -- active | completed | cancelled
  due_date date,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Account ledger — drives Debtors (receivable) and Creditors (payable)
-- amount: positive = increases what is owed (a charge/bill),
--         negative = reduces it (a payment / credit note).
-- ---------------------------------------------------------------------------
create table if not exists public.account_transactions (
  id bigint generated by default as identity primary key,
  account_type text not null,                   -- debtor | creditor
  customer_id uuid references public.customers(id) on delete cascade,
  supplier_id bigint references public.suppliers(id) on delete cascade,
  party_name text,
  txn_type text not null,                        -- invoice | bill | payment | credit_note | opening
  amount numeric(12,2) not null default 0,
  method text,
  reference text,
  doc_type text,
  doc_id text,
  notes text,
  txn_date date not null default current_date,
  created_by text,
  created_at timestamptz not null default now()
);
create index if not exists account_transactions_debtor_idx on public.account_transactions (account_type, customer_id);
create index if not exists account_transactions_creditor_idx on public.account_transactions (account_type, supplier_id);

-- ---------------------------------------------------------------------------
-- Stock takes (physical count + variance reconciliation)
-- ---------------------------------------------------------------------------
create table if not exists public.stock_takes (
  id bigint generated by default as identity primary key,
  reference text,
  status text not null default 'in_progress',   -- in_progress | completed | cancelled
  items jsonb not null default '[]'::jsonb,      -- [{product_id, name, sku, system_qty, counted_qty, variance}]
  total_variance integer not null default 0,
  total_items integer not null default 0,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

-- updated_at triggers
drop trigger if exists set_quotes_updated_at on public.quotes;
create trigger set_quotes_updated_at before update on public.quotes
  for each row execute function public.set_updated_at();
drop trigger if exists set_laybys_updated_at on public.laybys;
create trigger set_laybys_updated_at before update on public.laybys
  for each row execute function public.set_updated_at();
drop trigger if exists set_stock_takes_updated_at on public.stock_takes;
create trigger set_stock_takes_updated_at before update on public.stock_takes
  for each row execute function public.set_updated_at();

-- RLS: admin-managed
alter table public.quotes enable row level security;
alter table public.laybys enable row level security;
alter table public.account_transactions enable row level security;
alter table public.stock_takes enable row level security;

drop policy if exists "admins manage quotes" on public.quotes;
create policy "admins manage quotes" on public.quotes
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage laybys" on public.laybys;
create policy "admins manage laybys" on public.laybys
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage account_transactions" on public.account_transactions;
create policy "admins manage account_transactions" on public.account_transactions
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage stock_takes" on public.stock_takes;
create policy "admins manage stock_takes" on public.stock_takes
  for all using (public.is_admin()) with check (public.is_admin());

grant all on public.quotes, public.laybys, public.account_transactions, public.stock_takes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
