-- Repair job cards.
--
-- Replaces the carbon-copy book (the pictured pad runs to 1351). Because the
-- customer is usually not standing at the counter when the card is written,
-- acceptance happens on their own phone: staff send a link, the customer reads
-- the terms, signs on screen, and the signed card becomes a PDF.
--
-- The link is the only credential, so job_cards is NOT readable through the
-- API at all. Everything a guest can do goes through three SECURITY DEFINER
-- functions that take the token and return only the fields a customer should
-- see — notably never `pattern_pin`, which would otherwise turn a forwarded
-- WhatsApp message into a way to unlock the handset.

begin;

-- Numbering continues the physical book. Change the start value BEFORE the
-- first card is issued if your pad has moved past 1351.
create sequence if not exists public.job_card_number_seq start with 1352;

create table if not exists public.job_cards (
  id bigint generated by default as identity primary key,
  job_number integer not null unique default nextval('public.job_card_number_seq'),

  -- Customer
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,

  -- Handset
  handset_type text,
  imei text,
  fault text,
  physical_condition text,
  -- Android unlock pattern as dot indices ('1-2-5-8-9'), or a PIN/password.
  pattern_pin text,

  -- Money. handling_fee mirrors the non-refundable minimum on the printed card.
  deposit numeric(12,2) not null default 0,
  cost numeric(12,2) not null default 0,
  handling_fee numeric(12,2) not null default 200,

  -- Technician checklist: { lcd, touch, ringer, volume, power, charge,
  -- ear_speaker, mic, cameras, signed } -> boolean
  checks jsonb not null default '{}'::jsonb,
  technician text,

  status text not null default 'Awaiting acceptance',
  notes text,

  -- Guest acceptance
  accept_token text not null unique default encode(gen_random_bytes(24), 'hex'),
  accepted_at timestamptz,
  accepted_name text,
  accepted_signature text,
  accepted_user_agent text,

  -- Clause 9: repairs over N$350 need confirmation before work starts.
  quote_amount numeric(12,2),
  quote_note text,
  quote_sent_at timestamptz,
  quote_responded_at timestamptz,
  quote_approved boolean,

  collected_at timestamptz,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists job_cards_status_idx on public.job_cards (status, created_at desc);
create index if not exists job_cards_number_idx on public.job_cards (job_number desc);
create index if not exists job_cards_phone_idx on public.job_cards (customer_phone);

drop trigger if exists set_job_cards_updated_at on public.job_cards;
create trigger set_job_cards_updated_at before update on public.job_cards
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: staff only. Guests never touch the table directly.
-- ---------------------------------------------------------------------------
alter table public.job_cards enable row level security;

drop policy if exists "admins manage job cards" on public.job_cards;
create policy "admins manage job cards" on public.job_cards
  for all using (public.is_admin()) with check (public.is_admin());

revoke all on public.job_cards from anon;
grant all on public.job_cards to authenticated;
grant usage, select on sequence public.job_card_number_seq to authenticated;

-- ---------------------------------------------------------------------------
-- Guest surface.
--
-- One shared projection keeps the three functions from drifting apart on which
-- columns are safe to expose.
-- ---------------------------------------------------------------------------
create or replace function private.job_card_public_payload(c public.job_cards)
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'job_number', c.job_number,
    'customer_name', c.customer_name,
    'customer_phone', c.customer_phone,
    'handset_type', c.handset_type,
    'imei', c.imei,
    'fault', c.fault,
    'physical_condition', c.physical_condition,
    'deposit', c.deposit,
    'cost', c.cost,
    'handling_fee', c.handling_fee,
    'status', c.status,
    'checks', c.checks,
    'technician', c.technician,
    'created_at', c.created_at,
    'accepted_at', c.accepted_at,
    'accepted_name', c.accepted_name,
    'quote_amount', c.quote_amount,
    'quote_note', c.quote_note,
    'quote_sent_at', c.quote_sent_at,
    'quote_responded_at', c.quote_responded_at,
    'quote_approved', c.quote_approved
    -- pattern_pin, notes and accepted_signature are deliberately absent.
  );
$$;

/** Fetch a job card by its link token. Returns null-ish jsonb when unknown. */
create or replace function public.get_job_card(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  c public.job_cards%rowtype;
begin
  if p_token is null or length(p_token) < 20 then
    return jsonb_build_object('found', false);
  end if;

  select * into c from public.job_cards where accept_token = p_token;
  if not found then
    return jsonb_build_object('found', false);
  end if;

  return jsonb_build_object('found', true, 'job_card', private.job_card_public_payload(c));
end;
$$;

/**
 * Record the customer's acceptance of the terms.
 * Idempotent: a second submission returns the existing acceptance rather than
 * overwriting the signature that is already on file.
 */
create or replace function public.accept_job_card(
  p_token text,
  p_name text,
  p_signature text,
  p_user_agent text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  c public.job_cards%rowtype;
begin
  if coalesce(trim(p_name), '') = '' then
    return jsonb_build_object('ok', false, 'message', 'Please enter your full name.');
  end if;
  if coalesce(p_signature, '') = '' then
    return jsonb_build_object('ok', false, 'message', 'Please sign before accepting.');
  end if;
  -- A drawn signature is a PNG data URI; cap it so the column cannot be used
  -- as arbitrary storage by anyone holding a link.
  if length(p_signature) > 400000 then
    return jsonb_build_object('ok', false, 'message', 'Signature image is too large.');
  end if;

  select * into c from public.job_cards where accept_token = p_token for update;
  if not found then
    return jsonb_build_object('ok', false, 'message', 'This job card link is not valid.');
  end if;

  if c.accepted_at is not null then
    return jsonb_build_object(
      'ok', true,
      'already', true,
      'job_card', private.job_card_public_payload(c)
    );
  end if;

  update public.job_cards
  set accepted_at = now(),
      accepted_name = trim(p_name),
      accepted_signature = p_signature,
      accepted_user_agent = left(coalesce(p_user_agent, ''), 400),
      status = case when status = 'Awaiting acceptance' then 'Received' else status end
  where id = c.id
  returning * into c;

  return jsonb_build_object('ok', true, 'already', false,
                            'job_card', private.job_card_public_payload(c));
end;
$$;

/** Clause 9 approval: customer approves or declines a quote above N$350. */
create or replace function public.respond_job_card_quote(
  p_token text,
  p_approved boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  c public.job_cards%rowtype;
begin
  select * into c from public.job_cards where accept_token = p_token for update;
  if not found then
    return jsonb_build_object('ok', false, 'message', 'This job card link is not valid.');
  end if;
  if c.quote_sent_at is null then
    return jsonb_build_object('ok', false, 'message', 'No quote is awaiting your approval.');
  end if;
  if c.quote_responded_at is not null then
    return jsonb_build_object('ok', true, 'already', true,
                              'job_card', private.job_card_public_payload(c));
  end if;

  update public.job_cards
  set quote_responded_at = now(),
      quote_approved = p_approved,
      status = case when p_approved then 'Approved — in repair' else 'Quote declined' end
  where id = c.id
  returning * into c;

  return jsonb_build_object('ok', true, 'already', false,
                            'job_card', private.job_card_public_payload(c));
end;
$$;

-- The projection helper stays internal; only the three entry points are callable.
revoke all on function private.job_card_public_payload(public.job_cards) from public, anon, authenticated;
grant execute on function public.get_job_card(text) to anon, authenticated;
grant execute on function public.accept_job_card(text, text, text, text) to anon, authenticated;
grant execute on function public.respond_job_card_quote(text, boolean) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
